#!/bin/bash

function tracked(){
	msg="UNFIN"
	if [[ $# -gt 0 ]]; then
		msg="$msg: $*"
	fi
	git commit -am "$msg";
}

function all(){
	while read line; do
		local filename=$(echo $line | cut -b4-)
		git add "$filename"
	done < <(git status --porcelain | grep '^??')
	tracked "$@"
}

function reset(){
	if ! git rev-list --format=%B --max-count=1 HEAD | grep -qe '^UNFIN\($\|:\)'; then
		echo "previous commit was not unfinished"
		exit 1
	fi
	git reset HEAD\^
}

action="tracked"
if [[ "${1:0:2}" == "--" ]]; then
	action=${1:2}
	shift
fi

# validate and execute function
available=$(grep "^function" $0 | sed 's/function \([a-z]*\)(){/\1/g')
for it in ${available[@]}; do
	if [[ "$it" == "$action" ]]; then
		$action "$@"
		exit 0
	fi
done

echo "invalid action $action"
exit 1
